name: GitHub Test Custom Action
'on': workflow_dispatch
jobs:
  publish-test-results:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  test:
    name: Test
    needs: publish-test-results
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: ServiceNow DevOps Unit Test Results
        uses: ServiceNow/servicenow-devops-test-report@dev
        with:
          devops-integration-user-name: '${{ secrets.SN_DEVOPS_USER }}'
          devops-integration-user-password: '${{ secrets.SN_DEVOPS_PASSWORD }}'
          instance-url: '${{ secrets.SN_INSTANCE_NAME }}'
          tool-id: '${{ secrets.SN_ORCH_TOOL_ID }}'
          job-name: Test
          context-github: '${{ toJSON(github) }}'
          xml-report-filename: JestFolder/jest-junit.xml
          
  integrationTest:
    name: Integration  Test
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: ServiceNow DevOps NUnit Test Results
        uses: ServiceNow/servicenow-devops-test-report@dev
        with:
          devops-integration-user-name: '${{ secrets.SN_DEVOPS_USER }}'
          devops-integration-user-password: '${{ secrets.SN_DEVOPS_PASSWORD }}'
          instance-url: '${{ secrets.SN_INSTANCE_NAME }}'
          tool-id: '${{ secrets.SN_ORCH_TOOL_ID }}'
          job-name: Test
          context-github: '${{ toJSON(github) }}'
          xml-report-filename: Test-Type-Repo/blob/main/NunitFolder/NUnit.xml



          
      # - name: ServiceNow DevOps XUnit Test Results
      #   uses: ServiceNow/servicenow-devops-test-report@dev
      #   with:
      #     devops-integration-user-name: '${{ secrets.SN_DEVOPS_USER }}'
      #     devops-integration-user-password: '${{ secrets.SN_DEVOPS_PASSWORD }}'
      #     instance-url: '${{ secrets.SN_INSTANCE_NAME }}'
      #     tool-id: '${{ secrets.SN_ORCH_TOOL_ID }}'
      #     job-name: Test
      #     context-github: '${{ toJSON(github) }}'
      #     xml-report-filename: XUnitFolder/XUnit.xml
      # - name: ServiceNow DevOps MSTest Results
      #   uses: ServiceNow/servicenow-devops-test-report@dev
      #   with:
      #     devops-integration-user-name: '${{ secrets.SN_DEVOPS_USER }}'
      #     devops-integration-user-password: '${{ secrets.SN_DEVOPS_PASSWORD }}'
      #     instance-url: '${{ secrets.SN_INSTANCE_NAME }}'
      #     tool-id: '${{ secrets.SN_ORCH_TOOL_ID }}'
      #     job-name: Test
      #     context-github: '${{ toJSON(github) }}'
      #     xml-report-filename: MSTestFolder/MSTest.trx
